data_url <- "http://tinyurl.com/nhdfwd8v"
temp_file <- tempfile()
download.file(data_url, temp_file, mode="wb")
gwaslist=readRDS(temp_file)
unlink(temp_file)
library(ldscR)
data("hapmap3")
gwaslist=merge_intersect(gwas_data_list=gwaslist,ref_panel=hapmap3[,c("SNP","A1","A2")])
ZMatrix=cbind(gwaslist$driving$Zscore,gwaslist$computer$Zscore,gwaslist$TV$Zscore,gwaslist$schooling$Zscore,gwaslist$myopia$Zscore)
data("EURLDSC")
fitldsc=ldscR(GWAS_List=gwaslist,LDSC=EURLDSC,estimate_SE=T)
